import Head from "next/head"
import Navbar from "../components/Navbar"
export default function Activity(){
    return (
        <div className="z-20 min-h-screen bg-gradient-to-br from-cyan-600 to-blue-800" >
        <Head>
          <title>Personal pages</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
         <Navbar/>
          <div className="text-3xl font-bold py-4 text-white text-center">Experience </div>
          <div className="py-16">

        <div className="md:w-3/5 text-white flex-col  space-y-12 jet mx-auto px-12 flex border-dashed border-l-2">
          <div className="flex-col space-y-2" >
            <div className="text-2xl font-bold">Backend Developer Intern</div>
            <div className="text-xl font-bold">KMPlus</div>
            <div className="text-xl">March 2022 - Present</div>
          </div>
          <div className="flex-col space-y-2" >
            <div className="text-2xl font-bold">Divisi Pemasaran UKMK</div>
            <div className="text-xl font-bold">Universitas Jenderal Soedirman</div>
            <div className="text-xl">March 2022 - Present</div>
          </div>
          <div className="flex-col space-y-2" >
            <div className="text-2xl font-bold">Backend Developer Intern</div>
            <div className="text-xl font-bold">Lingotalk</div>
            <div className="text-xl">November 2021 - February 2022 &bull; 4 months</div>
          </div>
          <div className="flex-col space-y-2" >
            <div className="text-2xl font-bold">Frontend (Reactjs) Instructor</div>
            <div className="text-xl font-bold">Jabar Coding Camp</div>
            <div className="text-xl">August 2021 - September 2021 &bull; 1 months</div>
          </div>
        </div>
          </div>
      </div>
    )
}