import Head from 'next/head'
import Navbar from '../components/Navbar'
import Heading from '../components/Heading'

export default function Home() {
  return (
    <>
    <div className="z-20 min-h-screen bg-gradient-to-br from-cyan-600 to-blue-800" >
      <Head>
        <title>Personal pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <Navbar/>
       <Heading/>
    </div>
    </>
  )
}
